use_frameworks!

platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-art', :sources=>['cocopods-ios-local']

target 'EVRoute_Example' do
  pod 'EVRoute', :path => '../'

  target 'EVRoute_Tests' do
    inherit! :search_paths

    
  end
end
